serverMetadata:
  name: "test-server-dynamic"
  environment: "testing-remote"

packages:
  - name: "nginx"
    state: "latest"
  - name: "curl"
    state: "latest"
  # - name: "npm"
  #   state: "latest"
  - name: "ufw"
    state: "latest"

services:
  - name: "nginx"
    enabled: true
    state: "running"
    managed: false 

system:
  serviceManager: "docker-supervisor"
  containerized: true 

files:
  - path: "/etc/nginx/nginx.conf"
    content: |
      user nginx;
      worker_processes auto;
      events {
          worker_connections 1024;
      }
      http {
          server {
              listen 9002;
              server_name localhost;
              location / {
                  return 200 'Hello from a REMOTE config V2 - SUCCESS!\n';
              }
              location /status {
                  return 200 'Server status: V1 is now Running\n';
              }
          }
      }
    reloadCommand: "supervisorctl -c /etc/supervisor/supervisord.conf restart nginx"
