serverMetadata:
  name: "test-server-dynamic"
  environment: "testing-remote"

packages:
  - name: "nginx"
    state: "latest"
  - name: "curl"
    state: "latest"

services:
  - name: "nginx"
    enabled: true
    state: "running"

files:
  - path: "/etc/nginx/nginx.conf"
    content: |
      user nginx;
      worker_processes auto;
      events {
          worker_connections 1024;
      }
      http {
          server {
              listen 9002;
              server_name localhost;
              location / {
                  return 200 'Hello from REMOTE config V2 - SUCCESS!!\n';
              }
              location /status {
                  return 200 'Server status: V1 is now Running\n';
              }
          }
      }
    reloadService: "nginx" # Tell the agent to reload nginx
